# Generated by Django 6.0.3 on 2026-03-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claim',
            table='claims_claim',
        ),
    ]
