# Generated by Django 6.0.3 on 2026-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='incident_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='claim',
            table=None,
        ),
    ]
