# Generated by Django 6.0.3 on 2026-03-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_incident_name_alter_claim_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='incident_name',
        ),
        migrations.AddField(
            model_name='claim',
            name='amount_verification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='document_verification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_validity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='staff_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
