# Generated by Django 6.0.3 on 2026-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_claim_incident_name_claim_amount_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='claim',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
