# Generated by ChatGPT on 2026-03-17

from django.db import migrations


def forwards(apps, schema_editor):
    ClaimDocument = apps.get_model("claims", "ClaimDocument")
    ClaimDocument.objects.filter(document_type="id_proof").update(document_type="identity_proof")


def backwards(apps, schema_editor):
    ClaimDocument = apps.get_model("claims", "ClaimDocument")
    ClaimDocument.objects.filter(document_type="identity_proof").update(document_type="id_proof")


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_claim_recommended_amount_alter_claim_approved_amount_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
