# Generated by ChatGPT on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0007_update_identity_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("claim_form", "Claim Form"),
                    ("death_certificate", "Death Certificate"),
                    ("medical_report", "Medical Report"),
                    ("hospital_bill", "Hospital Bill"),
                    ("discharge_summary", "Discharge Summary"),
                    ("fir_copy", "FIR Copy"),
                    ("police_report", "Police Report"),
                    ("identity_proof", "Identity Proof"),
                    ("address_proof", "Address Proof"),
                    ("bank_proof", "Bank Proof"),
                    ("policy_copy", "Policy Copy"),
                    ("photos", "Photos / Evidence"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
