# Generated by Django 6.0.3 on 2026-03-17 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claimdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(upload_to='claims/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Only PDF or JPG/JPEG/PNG files are allowed.')]),
        ),
    ]
