# Generated by Django 6.0.3 on 2026-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_alter_claimdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='claimnote',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='claimnote',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimnote',
            name='is_visible_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claimnote',
            name='note_type',
            field=models.CharField(choices=[('customer', 'Customer Note'), ('internal', 'Internal Note')], default='internal', max_length=20),
        ),
    ]
