# Generated by Django 6.0.3 on 2026-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_alter_claimnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimassessment',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total bill amount from medical/hospital documents', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claimassessment',
            name='coverage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coverage percentage (e.g., 80.00 for 80%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='claimassessment',
            name='deductible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deductible amount to be subtracted', max_digits=12, null=True),
        ),
    ]
