# Generated by Django 6.0.3 on 2026-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claimassessment_bill_amount_claimassessment_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimant',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='claimant',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='claimant',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='claimant',
            name='id_proof_number',
        ),
        migrations.RemoveField(
            model_name='claimant',
            name='id_proof_type',
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_claim_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('medical', 'Medical'), ('theft', 'Theft'), ('death', 'Death'), ('maturity', 'Maturity'), ('surrender', 'Surrender'), ('disability', 'Disability'), ('critical_illness', 'Critical Illness'), ('hospitalization', 'Hospitalization'), ('property_damage', 'Property Damage'), ('fire', 'Fire'), ('natural_disaster', 'Natural Disaster'), ('third_party', 'Third Party Liability'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='final_claim_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('medical', 'Medical'), ('theft', 'Theft'), ('death', 'Death'), ('maturity', 'Maturity'), ('surrender', 'Surrender'), ('disability', 'Disability'), ('critical_illness', 'Critical Illness'), ('hospitalization', 'Hospitalization'), ('property_damage', 'Property Damage'), ('fire', 'Fire'), ('natural_disaster', 'Natural Disaster'), ('third_party', 'Third Party Liability'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimsettlement',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('medical', 'Medical'), ('theft', 'Theft'), ('death', 'Death'), ('maturity', 'Maturity'), ('surrender', 'Surrender'), ('disability', 'Disability'), ('critical_illness', 'Critical Illness'), ('hospitalization', 'Hospitalization'), ('property_damage', 'Property Damage'), ('fire', 'Fire'), ('natural_disaster', 'Natural Disaster'), ('third_party', 'Third Party Liability'), ('other', 'Other')], max_length=30),
        ),
    ]
