# Generated by Django 6.0.3 on 2026-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_remove_claimant_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_predicted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI predicted recommended claim amount', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='risk_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
