# Generated by Django 6.0.3 on 2026-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_claim_ai_predicted_amount_alter_claim_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Required for Motor Policy claims. Must match the policy vehicle number.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('claim_form', 'Claim Form'), ('identity_proof', 'Identity Proof (Aadhaar)'), ('address_proof', 'Address Proof'), ('bank_proof', 'Bank Proof'), ('policy_copy', 'Policy Copy'), ('rc_document', 'Registration Certificate (RC)'), ('death_certificate', 'Death Certificate'), ('property_proof', 'Property/Ownership Proof'), ('damage_proof', 'Damage Proof (Photos/Survey)'), ('hospital_bill', 'Hospital/Medical Bill'), ('repair_bill', 'Repair/Diagnostic Bill'), ('photos', 'Photos / Evidence'), ('other', 'Other Documents')], max_length=30),
        ),
    ]
