# Generated by Django 6.0.3 on 2026-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_claim_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
