# Generated by Django 6.0.3 on 2026-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_add_is_verified_to_claimdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_adjustment_factor',
            field=models.FloatField(blank=True, help_text='The weight or multiplier applied by AI (e.g. 0.75 for 75%)', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_calculation_logic',
            field=models.TextField(blank=True, help_text='Human-readable explanation of how AI arrived at the recommended amount'),
        ),
    ]
