# Generated by Django 6.0.3 on 2026-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_claim_ai_adjustment_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='ai_calculation_logic',
            field=models.TextField(blank=True, help_text='Human-readable explanation of how AI arrived at the recommended amount', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
