# Generated by Django 6.0.3 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_alter_claim_ai_calculation_logic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='fraud_explanation',
            field=models.TextField(blank=True, help_text='AI-generated fraud risk justification (Internal only)', null=True),
        ),
    ]
