# Generated by Django 6.0.3 on 2026-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0018_claim_fraud_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='ai_claim_type',
            field=models.CharField(blank=True, help_text='Automated classification of the claim based on description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, help_text='System confidence in the claim classification (0-100%)', null=True),
        ),
    ]
