# Generated by Django 6.0.3 on 2026-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_alter_claim_ai_claim_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='net_claimable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated as claimed_amount - deductible_amount', max_digits=12),
        ),
    ]
