# Generated by Django 6.0.3 on 2026-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_claim_net_claimable'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admission_days',
            field=models.IntegerField(default=0, help_text='Number of days hospitalized'),
        ),
        migrations.AddField(
            model_name='claim',
            name='diagnosis_severity',
            field=models.IntegerField(default=1, help_text='Severity of diagnosis (1: Normal, 5: Critical)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('network', 'Network Hospital')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='medication_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='number_of_tests',
            field=models.IntegerField(default=0, help_text='Number of diagnostic tests performed'),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_age',
            field=models.IntegerField(blank=True, help_text='Age of the patient at the time of claim', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='room_rent_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
