# Generated by Django 6.0.3 on 2026-03-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0021_claim_admission_days_claim_diagnosis_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='emergency_flag',
            field=models.BooleanField(default=False, help_text='Flag for immediate attention (e.g. ICU admission)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority_level',
            field=models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='priority_score',
            field=models.FloatField(default=0.0, help_text='Automated weight for admin sorting'),
        ),
    ]
