# Generated by Django 6.0.3 on 2026-03-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0022_claim_emergency_flag_claim_priority_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_decision',
            field=models.CharField(blank=True, choices=[('auto_process', 'Auto Process'), ('manual_review', 'Manual Review'), ('reject', 'Reject')], help_text='The final automated decision from the AI pipeline', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_drift_score',
            field=models.FloatField(default=0.0, help_text='Detected confidence drift from baseline'),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ai_version',
            field=models.CharField(default='v3.0', max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from invoices via OCR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='ml_model_version',
            field=models.CharField(default='xgb_baseline_v1', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_claim_type',
            field=models.CharField(blank=True, help_text='Automated classification (motor, health, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_predicted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI recommended amount AFTER logic and penalties', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, help_text='System confidence in classification (0-100%)', null=True),
        ),
        migrations.CreateModel(
            name='AIModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('fraud_precision', models.FloatField(default=0.0)),
                ('fraud_recall', models.FloatField(default=0.0)),
                ('non_fraud_precision', models.FloatField(default=0.0)),
                ('non_fraud_recall', models.FloatField(default=0.0)),
                ('health_score', models.FloatField(default=0.0, help_text='Consolidated 0-100 indicator')),
                ('suggested_actions', models.JSONField(blank=True, help_text='Actionable fixes based on root cause', null=True)),
                ('top_error_features', models.JSONField(blank=True, help_text='Features contributing most to disputes', null=True)),
                ('total_samples', models.IntegerField(default=0)),
                ('disputed_count', models.IntegerField(default=0)),
                ('average_drift', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'AI Model Metrics',
                'ordering': ['-date'],
                'unique_together': {('model_version', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClaimAIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='v3.0', max_length=10)),
                ('ai_claim_type', models.CharField(max_length=50)),
                ('ai_predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ai_risk_score', models.FloatField()),
                ('ai_decision', models.CharField(max_length=30)),
                ('ai_confidence', models.FloatField()),
                ('shap_values', models.JSONField(blank=True, help_text='Local feature importance values', null=True)),
                ('shadow_decision', models.CharField(blank=True, max_length=30, null=True)),
                ('shadow_predicted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('feature_vector', models.JSONField(blank=True, null=True)),
                ('human_decision', models.CharField(blank=True, max_length=30, null=True)),
                ('human_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to='claims.claim')),
            ],
            options={
                'verbose_name_plural': 'Claim AI History',
                'ordering': ['-created_at'],
            },
        ),
    ]
