# Generated by Django 6.0.3 on 2026-03-27 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0023_claim_ai_decision_claim_ai_drift_score_and_more'),
        ('policy', '0022_payment_direction_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsettlement',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Link to the master Payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_settlements', to='policy.payment'),
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim')),
            ],
            options={
                'verbose_name_plural': 'Claim Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
