# Generated by Django 6.0.3 on 2026-03-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0024_claimsettlement_payment_claimstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdocument',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for rejection or verification notes', null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
