# Generated by Django 6.0.3 on 2026-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0025_remove_claimdocument_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsettlement',
            name='settled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
