# Generated by Django 6.0.3 on 2026-03-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0026_claimsettlement_settled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAAR', 'Identity Proof (Aadhaar)'), ('HOSPITAL_BILL', 'Hospital / Medical Bill'), ('VEHICLE_RC', 'Vehicle Registration (RC)'), ('REPAIR_INVOICE', 'Repair / Workshop Invoice'), ('claim_form', 'Claim Form'), ('policy_copy', 'Policy Copy'), ('photos', 'Photos / Evidence'), ('other', 'Other Documents')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='remarks',
            field=models.TextField(blank=True, help_text='Mandatory for rejected documents to satisfy explainability requirements.', null=True),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified (Trustworthy)'), ('rejected', 'Rejected (Disputed/Invalid)')], default='pending', help_text='Tracks the transition from raw upload to verified asset.', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Identifies the human auditor responsible for the decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
