# Generated by Django 6.0.3 on 2026-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0027_alter_claimdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_reason',
            field=models.TextField(blank=True, help_text="Traceable explanation for the AI's risk score and predicted outcomes.", null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_version',
            field=models.CharField(default='v3.2', max_length=10),
        ),
    ]
