# Generated by Django 6.0.3 on 2026-03-27 13:01

import claims.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0028_claim_ai_reason_alter_claim_ai_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='ai_predicted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI recommended amount AFTER logic and penalties', max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from invoices via OCR', max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medication_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='net_claimable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated as claimed_amount - deductible_amount', max_digits=12, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='room_rent_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Required for Motor Policy claims. Must match the policy vehicle number.', max_length=20, null=True, validators=[claims.validators.VehicleNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='claimassessment',
            name='recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[claims.validators.PositiveAmountValidator()]),
        ),
        migrations.AlterField(
            model_name='claimsettlement',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, help_text='The actual amount paid to the claimant. Must be positive.', max_digits=12, validators=[claims.validators.PositiveAmountValidator()]),
        ),
    ]
