# Generated by Django 6.0.3 on 2026-03-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0029_alter_claim_ai_predicted_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='ai_reason',
        ),
        migrations.RemoveField(
            model_name='claimdocument',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='claimdocument',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='claimdocument',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='claimsettlement',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='claimsettlement',
            name='settled_at',
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_predicted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI recommended amount AFTER logic and penalties', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_version',
            field=models.CharField(default='v3.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from invoices via OCR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='deductible_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='medication_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='net_claimable',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated as claimed_amount - deductible_amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='room_rent_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='settled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Required for Motor Policy claims. Must match the policy vehicle number.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimassessment',
            name='recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document_type',
            field=models.CharField(choices=[('claim_form', 'Claim Form'), ('identity_proof', 'Identity Proof (Aadhaar)'), ('address_proof', 'Address Proof'), ('bank_proof', 'Bank Proof'), ('policy_copy', 'Policy Copy'), ('rc_document', 'Registration Certificate (RC)'), ('death_certificate', 'Death Certificate'), ('property_proof', 'Property/Ownership Proof'), ('damage_proof', 'Damage Proof (Photos/Survey)'), ('hospital_bill', 'Hospital/Medical Bill'), ('repair_bill', 'Repair/Diagnostic Bill'), ('photos', 'Photos / Evidence'), ('other', 'Other Documents')], max_length=30),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimsettlement',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='ClaimStatusHistory',
        ),
    ]
