# Generated by Django 6.0.3 on 2026-03-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0030_remove_claim_ai_reason_remove_claimdocument_remarks_and_more'),
        ('policy', '0027_payment_user_userpolicy_sum_insured_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='user_policy',
            field=models.ForeignKey(blank=True, help_text='The specific user-owned policy this claim is filed against.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policy.userpolicy'),
        ),
    ]
