# Generated by Django 6.0.3 on 2026-03-28 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0031_claim_user_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reported_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', help_text='Current lifecycle state of the dossier.', max_length=30),
        ),
    ]
