# Generated by Django 6.0.3 on 2026-04-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0033_add_public_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='allowed_diagnostics',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='allowed_room_rent',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='diagnostics_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital_risk_score',
            field=models.FloatField(default=0.1, help_text='Risk score of the provider'),
        ),
        migrations.AddField(
            model_name='claim',
            name='non_medical_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='user_risk_score',
            field=models.FloatField(default=0.05, help_text='Historical behavior score of the claimant'),
        ),
    ]
