# Generated by Django 6.0.3 on 2026-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0034_claim_allowed_diagnostics_claim_allowed_room_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admission_type',
            field=models.CharField(choices=[('routine', 'Routine (Scheduled)'), ('emergency', 'Emergency (Unscheduled)')], default='routine', help_text='Clinical urgency identifier for AI triage.', max_length=20),
        ),
    ]
