# Generated by Django 6.0.3 on 2026-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0035_claim_admission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_audit_note',
            field=models.TextField(blank=True, help_text='Deterministic AI generated audit note for the dossier.'),
        ),
    ]
