# Generated by Django 6.0.3 on 2026-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0036_claim_ai_audit_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Full text extracted via OCR for AI auditing and decisioning.', null=True),
        ),
    ]
