# Generated by Django 6.0.3 on 2026-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0037_claim_ocr_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='bill_amount',
            new_name='ocr_total_amount',
        ),
    ]
