# Generated by Django 6.0.3 on 2026-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0038_rename_bill_amount_claim_ocr_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='ocr_text',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='ocr_total_amount',
        ),
        migrations.AddField(
            model_name='claim',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from invoices via OCR', max_digits=12, null=True),
        ),
    ]
