# Generated by Django 6.0.3 on 2026-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0039_remove_claim_ocr_text_remove_claim_ocr_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Full text dump from the dossier (multi-document OCR merger).', null=True),
        ),
    ]
