# Generated by Django 6.0.3 on 2026-04-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0040_claim_ocr_text'),
        ('policy', '0034_userpolicy_nominee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_override',
            field=models.JSONField(blank=True, help_text='Records admin decision and justification when it differs from staff recommendation.', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Detailed assessment findings by staff.'),
        ),
        migrations.AddField(
            model_name='claim',
            name='staff_recommendation',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVIEW', 'Review')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('accident', 'Accident'), ('medical', 'Medical'), ('theft', 'Theft'), ('death', 'Death'), ('disability', 'Disability'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='final_claim_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('medical', 'Medical'), ('theft', 'Theft'), ('death', 'Death'), ('disability', 'Disability'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigation', 'Investigation'), ('staff_reviewed', 'Staff Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policy.userpolicy'),
        ),
    ]
