# Generated by Django 6.0.3 on 2026-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0041_claim_admin_override_claim_staff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_payout_backup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI Final Payable value before any human intervention', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Set to True if staff/admin manually changed the AI recommendation'),
        ),
        migrations.AddField(
            model_name='claim',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Mandatory justification for manual overrides', null=True),
        ),
    ]
