# Generated by Django 6.0.3 on 2026-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0042_claim_ai_payout_backup_claim_manual_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='fraud_probability',
            field=models.FloatField(blank=True, default=0.0, help_text='The Raw probability score from the XGBoost model (0-1)', null=True),
        ),
    ]
