# Generated by Django 6.0.3 on 2026-04-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0043_claim_fraud_probability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the dossier was assigned to a staff member.', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='deviation_score',
            field=models.FloatField(default=0.0, help_text='Calculated deviation between AI and Human recommendations.'),
        ),
        migrations.AddField(
            model_name='claim',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Proceed with AI Recommendation'), ('MODIFY', 'Manual Override / Adjustment'), ('REJECT', 'Formal Rejection')], max_length=15)),
                ('recommended_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ai_original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('throughput_value', models.DecimalField(decimal_places=2, help_text='Carried value of the original claim submission.', max_digits=12)),
                ('assigned_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('process_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('is_within_sla', models.BooleanField(default=True)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('deviation_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_reviews', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_review', to='claims.claim')),
            ],
        ),
    ]
