# Generated by Django 6.0.3 on 2026-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0044_claim_assigned_at_claim_deviation_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the auditing staff.', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='staff_recommendation',
            field=models.CharField(blank=True, help_text="Auditor's initial decision (Approve/Reject/Review).", max_length=50, null=True),
        ),
    ]
