# Generated by Django 6.0.3 on 2026-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0045_alter_claim_staff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorreview',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
