# Generated by Django 5.2.13 on 2026-04-14 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0046_auditorreview_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_engine_version',
            field=models.CharField(default='v2.0', help_text='Engine version that produced final_ai_recommendation.', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='final_ai_recommendation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest authoritative AI payout after full pipeline execution.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='human_override_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual auditor override amount (takes display priority over AI).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='initial_ai_prediction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FROZEN first estimate captured at claim submission time.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='prediction_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the AI recommendation was generated.', null=True),
        ),
        migrations.AlterField(
            model_name='auditorreview',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auditorreview',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_reviews', to='claims.claim'),
        ),
        migrations.AlterField(
            model_name='auditorreview',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_predicted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Legacy AI amount. Use final_ai_recommendation.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PayoutRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.CharField(max_length=500)),
                ('engine_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_logs', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Payout Recommendation Log',
                'verbose_name_plural': 'Payout Recommendation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
