# Generated by Django 5.2.13 on 2026-04-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0048_migrate_legacy_predictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimaihistory',
            old_name='ai_predicted_amount',
            new_name='ai_recommendation',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='ai_predicted_amount',
        ),
    ]
