# Generated by Django 5.2.13 on 2026-04-14 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0049_rename_ai_predicted_amount_claimaihistory_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(help_text='e.g. XGB_v3.2, HEALTH_v1.0', max_length=50, unique=True)),
                ('algorithm_type', models.CharField(help_text='XGBoost, RandomForest, Ensemble', max_length=100)),
                ('trained_at', models.DateTimeField()),
                ('dataset_hash', models.CharField(help_text='SHA-256 hash of the training dataset CSV', max_length=64)),
                ('feature_schema_version', models.CharField(help_text='Tracks changes in input feature engineering', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Current production model')),
                ('metrics', models.JSONField(blank=True, help_text='Snapshot of Precision, Recall, Accuracy', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Model Registry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='decision_engine_verdict',
            field=models.CharField(choices=[('auto_approve', 'Auto Approve ✅'), ('manual_review', 'Manual Review 🔍'), ('investigation', 'Flag for Investigation 🚨'), ('rejected', 'Rejected (Hard Rule) ❌')], db_index=True, default='manual_review', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='decision_orchestration_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='documentation_risk_score',
            field=models.FloatField(default=0.0, help_text='OCR quality / missing docs score (0-1)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_risk_score',
            field=models.FloatField(default=0.0, help_text='Probability of intentional fraud (0-1)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='leakage_risk_score',
            field=models.FloatField(default=0.0, help_text='Probability of overbilling/waste (0-1)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payout_uncertainty_score',
            field=models.FloatField(default=0.0, help_text='Confidence interval around recommendation (0-1)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='shap_narrative',
            field=models.TextField(blank=True, help_text='Human-readable summary of influencing factors.', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='top_features',
            field=models.JSONField(blank=True, help_text='Key features and their SHAP contributions (positive/negative).', null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='ocr_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of extracted text to detect duplicate invoices.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='model_version',
            field=models.ForeignKey(blank=True, help_text='The exact ML model version used for this specific assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.claimmodelversion'),
        ),
    ]
