# Generated by Django 5.2.13 on 2026-04-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0051_immutableauditledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ocr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from documents via OCR engine', max_digits=12, null=True),
        ),
    ]
