# Generated by Django 5.2.13 on 2026-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0052_claim_ocr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='additional_bill_requested',
            field=models.BooleanField(default=False, help_text='Automated trigger for more evidence'),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_amount_mismatch_ratio',
            field=models.FloatField(default=0.0, help_text='ABS(Declared - OCR) / OCR'),
        ),
        migrations.AddField(
            model_name='claim',
            name='declared_claim_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User-entered amount at submission', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='mismatch_flag',
            field=models.BooleanField(default=False, help_text='True if mismatch > threshold (e.g., 15%)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='mismatch_risk_score',
            field=models.FloatField(default=0.0, help_text='Derived risk penalty for amount variance'),
        ),
        migrations.AddField(
            model_name='claim',
            name='ocr_verified_bill_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all validated amounts from OCR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall confidence of the AI classification (0-100).', null=True),
        ),
    ]
