# Generated by Django 5.2.13 on 2026-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0053_claim_additional_bill_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='critical_mismatch_flag',
            field=models.BooleanField(default=False, help_text='Trigger for high-level fraud escalation.'),
        ),
        migrations.AddField(
            model_name='claim',
            name='integrity_status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('MINOR', 'Minor Variance'), ('MEDIUM', 'Medium Variance'), ('HIGH', 'High Variance'), ('CRITICAL', 'Critical Anomaly')], default='PASS', help_text='Classification of the amount mismatch severity.', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='manual_amount_confirmed',
            field=models.BooleanField(default=False, help_text='True if a human has explicitly confirmed the payout basis.'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payout_basis_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The authoritative amount chosen as basis for payout calculation.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payout_basis_source',
            field=models.CharField(choices=[('DECLARED', 'Declared Amount'), ('OCR', 'OCR Verified'), ('MANUAL', 'Manual Override'), ('AI_RECOMMENDED', 'AI Recommended')], default='DECLARED', help_text='Where the payout payout_basis_amount originated from.', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='review_hold_flag',
            field=models.BooleanField(default=False, help_text='Prevents automated settlement until review is cleared.'),
        ),
    ]
