# Generated by Django 5.2.13 on 2026-04-25 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0054_claim_critical_mismatch_flag_claim_integrity_status_and_more'),
        ('policy', '0036_integrity_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_amount_mismatch_ratio'], name='claim_mismatch_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['integrity_status'], name='claim_integrity_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['review_hold_flag'], name='claim_review_hold_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['critical_mismatch_flag'], name='claim_critical_mismatch_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['payout_basis_source'], name='claim_payout_basis_idx'),
        ),
    ]
