# Generated by Django 5.2.13 on 2026-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0055_integrity_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The monetary value of the AI risk reserve (deduction).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='integrity_status',
            field=models.CharField(choices=[('PASS', 'Pass (Verified)'), ('MINOR', 'Minor Variance'), ('MEDIUM', 'Medium Variance (Amber)'), ('HIGH', 'High Variance'), ('CRITICAL', 'Critical Anomaly (Red)')], default='PASS', help_text='Classification of the amount mismatch severity.', max_length=20),
        ),
    ]
