# Generated by Django 5.2.13 on 2026-05-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0056_claim_risk_amount_alter_claim_integrity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('staff_reviewed', 'Waiting Approval'), ('investigation', 'Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='claimaihistory',
            name='version',
            field=models.CharField(default='v3.0', max_length=50),
        ),
    ]
