# Generated by Django 6.0.3 on 2026-03-21 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 numeric digits.')])),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
