# Generated by Django 6.0.3 on 2026-03-27 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(help_text='Sensitive PII - Used for verification only as per AI Governance Rules.', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 numeric digits.')]),
        ),
    ]
