# Generated by Django 6.0.3 on 2026-03-27 13:01

import claims.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(help_text='Sensitive PII - Used for verification only as per AI Governance Rules.', max_length=12, unique=True, validators=[claims.validators.AadhaarValidator()]),
        ),
    ]
