# Generated by Django 6.0.3 on 2026-03-27 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 numeric digits.')]),
        ),
    ]
