# Generated by Django 6.0.3 on 2026-03-29 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_verification_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit numeric Aadhaar number.', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 numeric digits.')]),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Official document for identity validation.', null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the identity has been officially vetted.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='The timestamp when verification was completed.', null=True),
        ),
    ]
