# Generated by Django 6.0.3 on 2026-03-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_aadhaar_number_user_id_proof_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full legal name as per identity documents.', max_length=255, null=True),
        ),
    ]
