# Generated by Django 6.0.3 on 2026-04-02 07:20

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_userprofile_public_ids(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    for profile in UserProfile.objects.filter(public_id__isnull=True).iterator():
        profile.public_id = uuid.uuid4()
        profile.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_userprofile_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='AadhaarKYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_full_name', models.CharField(blank=True, max_length=255)),
                ('submitted_aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('extracted_number', models.CharField(blank=True, max_length=12)),
                ('source_document_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to='accounts.userprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aadhaar KYC Verification',
                'verbose_name_plural': 'Aadhaar KYC Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
