# Generated by Django 5.2.13 on 2026-05-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_standardize_kyc_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarkycverification',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('manual_review', 'Manual Review'), ('rejected', 'Rejected'), ('approved_override', 'Approved by Admin'), ('rejected_override', 'Rejected by Admin'), ('escalated', 'Escalated to Manual Review')], default='manual_review', max_length=20),
        ),
    ]
