# Generated by Django 5.2.13 on 2026-08-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_aadhaarkycverification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('email_verify', 'Email Verification'), ('phone_verify', 'Phone Verification')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session_key', models.CharField(db_index=True, max_length=64)),
            ],
        ),
    ]
