# Generated by Django 5.2.13 on 2026-08-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_otpverification_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
