# Generated by Django 5.2.13 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_otpverification_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
    ]
