# Generated by Django 6.0.3 on 2026-03-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_insurer_policytype_alter_policy_insurer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policyholder',
            options={'verbose_name_plural': 'Policy Holders'},
        ),
        migrations.AddField(
            model_name='policy',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policy.insurer'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policy.policytype'),
        ),
        migrations.AlterModelTable(
            name='policy',
            table='policy_policy',
        ),
        migrations.AlterModelTable(
            name='policyholder',
            table='policy_policyholder',
        ),
    ]
