# Generated by Django 6.0.3 on 2026-03-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_policy_deductible_amount'),
        ('policy', '0005_alter_policy_options_alter_policyholder_options_and_more'),
    ]

    operations = [
    ]
