# Generated by Django 6.0.3 on 2026-03-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_merge_20260315_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='deductible_amount',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='insurer',
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
