# Generated by Django 6.0.3 on 2026-03-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_remove_policy_deductible_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coverage_details', models.TextField(blank=True, help_text='Details about what is covered')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions for this plan')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.insurer')),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.policytype')),
            ],
            options={
                'verbose_name': 'Policy Plan',
                'verbose_name_plural': 'Policy Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_policies', to='policy.policyplan'),
        ),
    ]
