# Generated by Django 6.0.3 on 2026-03-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_policyplan_policy_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='premium',
        ),
    ]
