# Generated by Django 6.0.3 on 2026-03-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_remove_policy_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='policy.policyholder'),
        ),
    ]
