# Generated by Django 6.0.3 on 2026-03-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0011_policyholder_join_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyholder',
            options={'verbose_name_plural': 'Policy Purchases'},
        ),
    ]
