# Generated by Django 6.0.3 on 2026-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0012_alter_policyholder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Coverage percentage for claims (e.g., 80.00 for 80%)', max_digits=5),
        ),
    ]
