# Generated by Django 6.0.3 on 2026-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_policy_coverage_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='gross_premium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
