# Generated by Django 6.0.3 on 2026-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0014_policy_base_premium_policy_gross_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='rc_upload',
            field=models.FileField(blank=True, help_text='Required for Motor Policies', null=True, upload_to='policy_rc/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Required for Motor Policies', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
