# Generated by Django 6.0.3 on 2026-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_policy_rc_upload_policy_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
