# Generated by Django 6.0.3 on 2026-03-22 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0016_policy_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when admin reviewed this application', null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Reason for rejection or additional notes from admin')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='policy.policy')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Application',
                'verbose_name_plural': 'Policy Applications',
                'db_table': 'policy_policyapplication',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'policy'), name='unique_user_policy_application')],
            },
        ),
    ]
