# Generated by Django 6.0.3 on 2026-03-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0017_add_policy_application_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='rc_upload',
            field=models.FileField(blank=True, help_text='RC document upload (Motor policies only)', null=True, upload_to='application_rc/'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number (Motor policies only)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text="Auto-generated unique certificate number for this user's coverage", max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('rc_upload', models.FileField(blank=True, null=True, upload_to='userpolicy_rc/')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_policies', to='policy.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Policy',
                'verbose_name_plural': 'User Policies',
                'db_table': 'policy_userpolicy',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'policy'), name='unique_user_policy_ownership')],
            },
        ),
    ]
