# Generated by Django 6.0.3 on 2026-03-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0018_add_userpolicy_and_application_motor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid including taxes', max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='credit_card', max_length=20)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier from payment gateway', max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, help_text='Reference ID from payment gateway', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text="Description of the payment (e.g., 'Policy Premium - Annual')")),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the payment')),
                ('payment_metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata (gateway response, etc.)')),
                ('user_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='policy.userpolicy')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'policy_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='policy_paym_transac_f3025d_idx'), models.Index(fields=['payment_status'], name='policy_paym_payment_c68f9c_idx'), models.Index(fields=['created_at'], name='policy_paym_created_cddc58_idx')],
            },
        ),
    ]
