# Generated by Django 6.0.3 on 2026-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0019_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('grace', 'Grace Period'), ('lapsed', 'Lapsed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
