# Generated by Django 6.0.3 on 2026-03-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_claim_net_claimable'),
        ('policy', '0020_alter_userpolicy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PREMIUM_PAYMENT', 'Premium Payment'), ('CLAIM_SETTLEMENT', 'Claim Settlement')], default='PREMIUM_PAYMENT', max_length=20),
        ),
    ]
