# Generated by Django 6.0.3 on 2026-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0021_payment_claim_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('CREDIT', 'Credit (Inflow/Premium)'), ('DEBIT', 'Debit (Outflow/Settlement)')], default='CREDIT', help_text='CREDIT for premiums, DEBIT for claim payouts', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('neft', 'NEFT/RTGS')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PREMIUM_PAYMENT', 'Premium Payment'), ('CLAIM_SETTLEMENT', 'Claim Settlement')], default='PREMIUM_PAYMENT', max_length=20, verbose_name='Transaction Title'),
        ),
    ]
