# Generated by Django 6.0.3 on 2026-03-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0022_payment_direction_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='sum_insured_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initially set to policy sum_insured', max_digits=12, null=True),
        ),
    ]
