# Generated by Django 6.0.3 on 2026-03-27 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0024_payment_user_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Format: MH12AB1234. AI Governance ensures only valid formats are processed.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Invalid format. Expected like 'MH12AB1234' (Standard Indian Vehicle Format).", regex='^[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{4}$')]),
        ),
    ]
