# Generated by Django 6.0.3 on 2026-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0025_alter_userpolicy_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpolicy',
            name='sum_insured_remaining',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PREMIUM_PAYMENT', 'Premium Payment'), ('CLAIM_SETTLEMENT', 'Claim Settlement')], default='PREMIUM_PAYMENT', max_length=20, verbose_name='Transaction Title'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
