# Generated by Django 6.0.3 on 2026-03-27 14:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0026_remove_payment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='sum_insured_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initially set to policy sum_insured', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PREMIUM', 'Premium Payment'), ('SETTLEMENT', 'Claim Settlement')], default='PREMIUM', max_length=20, verbose_name='Transaction Title'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Format: MH12AB1234. AI Governance ensures only valid formats are processed.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Invalid format. Expected like 'MH12AB1234' (Standard Indian Vehicle Format).", regex='^[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{4}$')]),
        ),
    ]
