# Generated by Django 6.0.3 on 2026-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0027_payment_user_userpolicy_sum_insured_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
