# Generated by Django 6.0.3 on 2026-03-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0028_policy_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard premium amount for this policy (Admins only)', max_digits=12),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='final_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The locked premium amount at the time of purchase', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the policy premium has been paid'),
        ),
        migrations.AlterField(
            model_name='userpolicy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('grace', 'Grace Period'), ('lapsed', 'Lapsed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
