# Generated by Django 6.0.3 on 2026-03-29 04:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0029_policy_premium_amount_userpolicy_final_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='admin_premium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Admin premium percentage (e.g. 6.00 for 6%). Applied on top of base_premium.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard premium amount override (Admins only)', max_digits=12),
        ),
    ]
