# Generated by Django 6.0.3 on 2026-03-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0030_policy_admin_premium_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpolicy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (Awaiting Payment)'), ('rejected', 'Rejected'), ('active', 'Active'), ('grace', 'Grace Period'), ('lapsed', 'Lapsed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
