# Generated by Django 6.0.3 on 2026-04-02 07:20

import uuid

from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model_names = [
        "UserProfile",
        "UserPolicy",
        "Payment",
        "Policy",
        "PolicyDocument",
        "PolicyApplication",
    ]

    for model_name in model_names:
        model = apps.get_model("policy", model_name)
        seen = set()
        rows_to_update = []

        for row in model.objects.using(db_alias).all().iterator():
            current = getattr(row, "public_id", None)
            current_str = str(current) if current else ""

            if not current_str or current_str in seen:
                row.public_id = uuid.uuid4()
                current_str = str(row.public_id)
                while current_str in seen:
                    row.public_id = uuid.uuid4()
                    current_str = str(row.public_id)
                rows_to_update.append(row)

            seen.add(current_str)

        if rows_to_update:
            model.objects.using(db_alias).bulk_update(rows_to_update, ["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0031_alter_userpolicy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="userpolicy",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="policyapplication",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="userpolicy",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("PREMIUM_PAYMENT", "Premium Payment"),
                    ("CLAIM_SETTLEMENT", "Claim Settlement"),
                ],
                default="PREMIUM",
                max_length=20,
                verbose_name="Transaction Title",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="policyapplication",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
