# Generated by Django 6.0.3 on 2026-04-03 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0032_public_id_schema_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policytype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Policy Category', 'verbose_name_plural': 'Policy Categories'},
        ),
        migrations.AddField(
            model_name='policytype',
            name='category_type',
            field=models.CharField(choices=[('medical', 'Medical / Health'), ('vehicle', 'Vehicle / Motor'), ('life', 'Life Insurance'), ('general', 'General / Other')], default='general', help_text='AI Context: helps classify this category for automated processing.', max_length=20),
        ),
        migrations.AddField(
            model_name='policytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policytype',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
