# Generated by Django 6.0.3 on 2026-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0033_alter_policytype_options_policytype_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='nominee_name',
            field=models.CharField(blank=True, help_text='Registered Nominee for Life/Death benefits.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='nominee_relationship',
            field=models.CharField(blank=True, help_text='Relationship of the nominee to the policyholder.', max_length=50, null=True),
        ),
    ]
