# Generated by Django 5.2.13 on 2026-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0034_userpolicy_nominee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='room_rent_limit_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capped room rent per day. 0 means unlimited / no cap.', max_digits=10),
        ),
    ]
