# Generated by Django 5.2.13 on 2026-04-25 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0035_policy_room_rent_limit_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='room_rent_limit_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Capped room rent per day. 0 means unlimited / no cap.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
