# Generated by Django 5.2.13 on 2026-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0036_integrity_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='room_penalty_enabled',
            field=models.BooleanField(default=True, help_text='Governance: Whether AI should calculate and apply room rent excess penalties for this policy plan.'),
        ),
    ]
