# Generated by Django 5.2.13 on 2026-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
    ]
