# Generated by Django 5.2.13 on 2026-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantsession_is_escalated_escalationticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='feedback_value',
            field=models.IntegerField(blank=True, choices=[(1, 'Positive'), (-1, 'Negative')], null=True),
        ),
    ]
