# Generated by Django 5.2.13 on 2026-04-23 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_assistantmessage_feedback_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='guest', max_length=20)),
                ('message_text', models.TextField()),
                ('detected_intent', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('response_source', models.CharField(choices=[('faq', 'Rule Engine'), ('db', 'Database Lookup'), ('llm', 'Neural Fallback'), ('escalation', 'Human Handoff')], max_length=50)),
                ('response_time_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Neural Audit Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
