# Generated by Django 6.0.3 on 2026-04-10 08:22

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_expires_at_notification_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_7088ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_f2898f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_expires_4f3289_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_cleared',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_claim_id',
            field=models.UUIDField(blank=True, help_text='Reference to a Claim public_id', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='role_target',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Auditor'), ('policyholder', 'Policyholder')], default='policyholder', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AddField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'is_cleared'], name='notificatio_user_id_b2f490_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_entity_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
