# Generated by Django 5.2.13 on 2026-04-24 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_notificatio_user_id_7088ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivered_email',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_push',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_sms',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_error',
            field=models.TextField(blank=True, help_text='Stores specific error messages from SMTP/Twilio', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_payment_id',
            field=models.UUIDField(blank=True, help_text='Reference to a PremiumPayment public_id', null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Alerts')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS Alerts')),
                ('realtime_enabled', models.BooleanField(default=True, verbose_name='In-App Real-time')),
                ('claim_updates', models.BooleanField(default=True, verbose_name='Claim Life-cycle')),
                ('kyc_alerts', models.BooleanField(default=True, verbose_name='Identity Verification')),
                ('payment_reminders', models.BooleanField(default=True, verbose_name='Premium Schedules')),
                ('marketing_updates', models.BooleanField(default=False, verbose_name='Newsletter & Offers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
