# Generated by ChatGPT on 2026-03-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policy", "0008_policyplan_policy_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_premium", models.DecimalField(decimal_places=2, max_digits=12)),
                ("gst_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("gst_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("gross_premium", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("payment_frequency", models.CharField(choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly")], max_length=20)),
                ("total_installments", models.PositiveIntegerField(default=1)),
                ("installment_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("auto_debit_enabled", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="premium_schedules", to="policy.policy")),
            ],
        ),
        migrations.CreateModel(
            name="PremiumPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("upcoming", "Upcoming"), ("paid", "Paid"), ("overdue", "Overdue")], default="upcoming", max_length=20)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("schedule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="premiums.premiumschedule")),
            ],
            options={
                "ordering": ["due_date", "installment_number"],
                "unique_together": {("schedule", "installment_number")},
            },
        ),
    ]
