# Generated by Django 6.0.3 on 2026-03-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_policy_rc_upload_policy_vehicle_number_and_more'),
        ('premiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumschedule',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_schedule', to='policy.policy'),
        ),
    ]
