# Generated by Django 6.0.3 on 2026-03-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0020_alter_userpolicy_status'),
        ('premiums', '0002_alter_premiumschedule_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumschedule',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='premiumschedule',
            name='user_policy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_schedule', to='policy.userpolicy'),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('lapsed', 'Lapsed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumschedule',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_schedules', to='policy.policy'),
        ),
    ]
