# Generated by Django 6.0.3 on 2026-03-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0022_payment_direction_alter_payment_payment_method_and_more'),
        ('premiums', '0003_premiumschedule_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Link to the master Payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_installments', to='policy.payment'),
        ),
    ]
