# Generated by Django 6.0.3 on 2026-03-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiums', '0004_premiumpayment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='payment',
        ),
    ]
