# Generated by Django 6.0.3 on 2026-04-02 07:20

import uuid

from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    model_names = [
        "PremiumSchedule",
        "PremiumPayment",
    ]

    for model_name in model_names:
        model = apps.get_model("premiums", model_name)
        rows = list(model.objects.using(db_alias).filter(public_id__isnull=True))
        if not rows:
            continue

        for row in rows:
            row.public_id = uuid.uuid4()

        model.objects.using(db_alias).bulk_update(rows, ["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('premiums', '0005_remove_premiumpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='public_id',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='premiumschedule',
            name='public_id',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='premiumpayment',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='premiumschedule',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
